### ISSUE TITLE
Linux下编译错误

### ISSUE THREAD

**Issue by skykeyjoker** [Chen-and-Sim/SmartChordGen#1]
在Linux下编译时出现错误：
Interface.h头文件引用出错
```
#include <QFileinfo>
...
#include "./chord.h"
#include "./functions.h"
```
为支持多平台，推荐您更改为:
```
#include <QFileInfo>  //Info首字母大写
...
#include "chord.h"
#include "functions.h"
```

**Comment by rcswex** [comment]
非常感谢您对我们项目的兴趣，我们会修改近日更新。

**Comment by skykeyjoker** [comment]
感谢您的回复！另外希望您能改进一下第三方库的调用，d3dcompiler作为微软专用库，无法在linux下运行。您的项目能替很多用户提供极大的便利，虽然不能胜任，我也想代表linux用户来请求您对第三方库的调用进行一些改进，谢谢您！

**Comment by rcswex** [comment]
> 感谢您的回复！另外希望您能改进一下第三方库的调用，d3dcompiler作为微软专用库，无法在linux下运行。您的项目能替很多用户提供极大的便利，虽然不能胜任，我也想代表linux用户来请求您对第三方库的调用进行一些改进，谢谢您！

感谢建议！头文件（.h）改好的近日将上传更新 repo；目前考虑释出一个 Linux 版本，但时间可能较长需一周以上，请耐心等待。

**Comment by skykeyjoker** [comment]
感谢您的回复！

**Comment by rcswex** [comment]
> 感谢您的回复！

头文件（.h）已修改，d3dcompiler 将在一周时间内另发布为 Linux 版，请您继续对本项目提出宝贵意见，不胜感激！

**Comment by rcswex** [comment]
@skykeyjoker Linux 版已推出，下载地址为：https://github.com/Chen-and-Sim/SmartChordGen/releases/download/v2.5/SmartChordGen.v2.5.0808.Linux.zip ，请您继续对本项目提出宝贵意见，不胜感激！
