### ISSUE TITLE
建议支持高DPI缩放

### ISSUE THREAD

**Issue by judgeou** [Chen-and-Sim/SmartChordGen#2]
![image](https://user-images.githubusercontent.com/2416816/89099208-30bdab80-d420-11ea-9e01-6a4d79292517.png)

![image](https://user-images.githubusercontent.com/2416816/89099292-bb9ea600-d420-11ea-8844-4542cb9aeeb5.png)

**Comment by rcswex** [comment]
@judgeou ：经改进，现支持自动适应比例缩放并通过了 1440×900、125% 下的测试。请到 Release 下载新安装包并测试是否有改善？

**Comment by rcswex** [comment]
@judgeou 现在版本已修复至高分辨率 250% 测试下可正常显示，请在 https://github.com/Chen-and-Sim/SmartChordGen/releases/tag/v2.0.0730  下载最新版本，应已恢复正常，如仍有问题请继续报告 issues，使用愉快！

**Comment by rcswex** [comment]
@judgeou 
现在版本已修复至高分辨率 250% 测试下可正常显示，请在 https://github.com/Chen-and-Sim/SmartChordGen/releases/tag/v2.0.0730 下载最新版本，应已恢复正常，如仍有问题请继续报告 issues，使用愉快！

**Comment by judgeou** [comment]
GOOD, 完全正常

**Comment by rcswex** [comment]
> GOOD, 完全正常

以后多多来提意见哦！
