### ISSUE TITLE
下载速度好慢啊

### ISSUE THREAD

**Issue by ccartermices** [Chen-and-Sim/SmartChordGen#3]
有更好的下载链接吗？

**Comment by rcswex** [comment]
你在哪里？国内GitHub访问慢试一下科学上网。

**Comment by rcswex** [comment]
> 有更好的下载链接吗？

你在哪里？国内GitHub访问慢试一下科学上网。

**Comment by rcswex** [comment]
您好！对于下载慢，提供百度网盘下载：链接：https://pan.baidu.com/s/1MpK2o_zQpqSp1ap-xm7jxQ ，提取码：1234 。感谢报告情况，使用愉快！
