### ISSUE TITLE
默认生成路径在哪里

### ISSUE THREAD

**Issue by Algoroxyolo** [Chen-and-Sim/SmartChordGen#4]

**Comment by rcswex** [comment]
> _No description provided._

感谢提出疑问，默认生成路径为 \output\ ，已加入 README 信息中哦。

**Comment by rcswex** [comment]
在 3.0.2021 版本中更新：已将生成路径改为系统桌面。

**Comment by rcswex** [comment]
> _No description provided._

在 3.0.2021 版本中更新：已将生成路径改为系统桌面。

**Comment by rcswex** [comment]
> _No description provided._

在 3.0.2021 版本中更新：已将生成路径改为系统桌面；同时，用户可点击文件名输入框左边的「齿轮」按钮选择输出路径。

**Comment by rcswex** [comment]
> _No description provided._
在 3.0.2021 版本中更新：已将生成路径改为系统桌面；同时，用户可点击文件名输入框左边的「齿轮」按钮以选择生成路径。
