### ISSUE TITLE
Linux下无法运行==

### ISSUE THREAD

**Issue by skykeyjoker** [Chen-and-Sim/SmartChordGen#6]
下载了您发布的最新Linux版本，然而不幸的是并不能运行。
```
segmentation fault (core dumped)  ./SmartChordGen
```
环境为Archlinux，已经保证过qt5运行环境完整，可编译运行source下的工程文件。
经测试，删除bin目录下的qt.conf后可运行。
感谢您的贡献！

**Comment by rcswex** [comment]
> 下载了您发布的最新Linux版本，然而不幸的是并不能运行。
> 
> ```
> segmentation fault (core dumped)  ./SmartChordGen
> ```
> 
> 环境为Archlinux，已经保证过qt5运行环境完整，可编译运行source下的工程文件。
> 经测试，删除bin目录下的qt.conf后可运行。
> 感谢您的贡献！

感谢您对项目的支持，我们会把 qt.conf 删除。请在使用过程中多多给项目提意见！
